name = "football-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
WORKER_BASE_URL = "https://football-worker.mahdijadir38.workers.dev"

[[kv_namespaces]]
binding = "FOOTBALL_KV"
id = "55d5d0377bf8450fb77a6e77f6fd7dce"

[triggers]
crons = [
  "* * * * *",
  "0 */6 * * *",
  "*/20 * * * *"
]
